"""schema inicial

Revision ID: 86c95736966c
Revises: 
Create Date: 2026-09-13 23:00:17.722430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86c95736966c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('categoria_pai_id', sa.UUID(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_pai_id'], ['categorias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_categoria_pai_id'), 'categorias', ['categoria_pai_id'], unique=False)
    op.create_index(op.f('ix_categorias_slug'), 'categorias', ['slug'], unique=True)
    op.create_table('fabricantes_veiculos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('marcas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_marcas_slug'), 'marcas', ['slug'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('carrinhos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('sessao_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'CONVERTIDO', 'ABANDONADO', name='status_carrinho'), nullable=False),
    sa.Column('canal', sa.Enum('WEB', 'ASSISTENTE', name='canal'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrinhos_sessao_id'), 'carrinhos', ['sessao_id'], unique=False)
    op.create_index(op.f('ix_carrinhos_usuario_id'), 'carrinhos', ['usuario_id'], unique=False)
    op.create_table('enderecos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('logradouro', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enderecos_usuario_id'), 'enderecos', ['usuario_id'], unique=False)
    op.create_table('modelos_veiculos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fabricante_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fabricante_id'], ['fabricantes_veiculos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelos_veiculos_fabricante_id'), 'modelos_veiculos', ['fabricante_id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_pedido', sa.String(length=30), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('AGUARDANDO_PAGAMENTO', 'PAGAMENTO_APROVADO', 'SEPARANDO_PEDIDO', 'ENVIADO', 'SAIU_PARA_ENTREGA', 'ENTREGUE', 'CANCELADO', name='status_pedido'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('frete', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('canal', sa.Enum('WEB', 'ASSISTENTE', name='canal'), nullable=False),
    sa.Column('endereco_entrega', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_numero_pedido'), 'pedidos', ['numero_pedido'], unique=True)
    op.create_index(op.f('ix_pedidos_status'), 'pedidos', ['status'], unique=False)
    op.create_index(op.f('ix_pedidos_usuario_id'), 'pedidos', ['usuario_id'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('marca_id', sa.UUID(), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('codigo_peca', sa.String(length=80), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_promocional', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('meses_garantia', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('meses_garantia >= 0', name='produtos_meses_garantia_check'),
    sa.CheckConstraint('preco >= 0', name='produtos_preco_positivo_check'),
    sa.CheckConstraint('preco_promocional IS NULL OR preco_promocional < preco', name='produtos_preco_promocional_menor_check'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_ativo'), 'produtos', ['ativo'], unique=False)
    op.create_index(op.f('ix_produtos_categoria_id'), 'produtos', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_produtos_codigo_peca'), 'produtos', ['codigo_peca'], unique=False)
    op.create_index(op.f('ix_produtos_marca_id'), 'produtos', ['marca_id'], unique=False)
    op.create_index(op.f('ix_produtos_sku'), 'produtos', ['sku'], unique=True)
    op.create_index(op.f('ix_produtos_slug'), 'produtos', ['slug'], unique=True)
    op.create_table('sessoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalizada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canal_inicial', sa.Enum('WEB', 'ASSISTENTE', name='canal'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_usuario_id'), 'sessoes', ['usuario_id'], unique=False)
    op.create_table('especificacoes_produtos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('especificacoes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_especificacoes_produtos_produto_id'), 'especificacoes_produtos', ['produto_id'], unique=True)
    op.create_table('estoques',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('quantidade_reservada', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantidade >= 0', name='estoques_quantidade_positiva_check'),
    sa.CheckConstraint('quantidade_reservada <= quantidade', name='estoques_reservada_menor_quantidade_check'),
    sa.CheckConstraint('quantidade_reservada >= 0', name='estoques_quantidade_reservada_positiva_check'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoques_produto_id'), 'estoques', ['produto_id'], unique=True)
    op.create_table('eventos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_evento', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sessao_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('canal', sa.Enum('WEB', 'ASSISTENTE', name='canal'), nullable=False),
    sa.Column('propriedades', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessoes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_nome_evento'), 'eventos', ['nome_evento'], unique=False)
    op.create_index(op.f('ix_eventos_sessao_id'), 'eventos', ['sessao_id'], unique=False)
    op.create_index(op.f('ix_eventos_usuario_id'), 'eventos', ['usuario_id'], unique=False)
    op.create_table('imagens_produtos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('posicao', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagens_produtos_produto_id'), 'imagens_produtos', ['produto_id'], unique=False)
    op.create_table('itens_carrinho',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('carrinho_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantidade > 0', name='itens_carrinho_quantidade_positiva_check'),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinhos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrinho_id', 'produto_id', name='itens_carrinho_carrinho_produto_unique')
    )
    op.create_index(op.f('ix_itens_carrinho_carrinho_id'), 'itens_carrinho', ['carrinho_id'], unique=False)
    op.create_index(op.f('ix_itens_carrinho_produto_id'), 'itens_carrinho', ['produto_id'], unique=False)
    op.create_table('itens_pedido',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('nome_produto', sa.String(length=200), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_pedido_pedido_id'), 'itens_pedido', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_itens_pedido_produto_id'), 'itens_pedido', ['produto_id'], unique=False)
    op.create_table('variantes_veiculos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('modelo_id', sa.UUID(), nullable=False),
    sa.Column('ano_inicio', sa.SmallInteger(), nullable=False),
    sa.Column('ano_fim', sa.SmallInteger(), nullable=False),
    sa.Column('motor', sa.String(length=50), nullable=False),
    sa.Column('versao', sa.String(length=100), nullable=True),
    sa.Column('combustivel', sa.String(length=30), nullable=False),
    sa.Column('cambio', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_veiculos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variantes_veiculos_modelo_id'), 'variantes_veiculos', ['modelo_id'], unique=False)
    op.create_table('compatibilidade_produtos_veiculos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('variante_veiculo_id', sa.UUID(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_veiculo_id'], ['variantes_veiculos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'variante_veiculo_id', name='compatibilidade_produto_variante_unique')
    )
    op.create_index(op.f('ix_compatibilidade_produtos_veiculos_produto_id'), 'compatibilidade_produtos_veiculos', ['produto_id'], unique=False)
    op.create_index(op.f('ix_compatibilidade_produtos_veiculos_variante_veiculo_id'), 'compatibilidade_produtos_veiculos', ['variante_veiculo_id'], unique=False)
    op.create_table('veiculos_usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('variante_veiculo_id', sa.UUID(), nullable=False),
    sa.Column('ano', sa.SmallInteger(), nullable=False),
    sa.Column('apelido', sa.String(length=80), nullable=True),
    sa.Column('placa', sa.String(length=10), nullable=True),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_veiculo_id'], ['variantes_veiculos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veiculos_usuarios_usuario_id'), 'veiculos_usuarios', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_veiculos_usuarios_variante_veiculo_id'), 'veiculos_usuarios', ['variante_veiculo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veiculos_usuarios_variante_veiculo_id'), table_name='veiculos_usuarios')
    op.drop_index(op.f('ix_veiculos_usuarios_usuario_id'), table_name='veiculos_usuarios')
    op.drop_table('veiculos_usuarios')
    op.drop_index(op.f('ix_compatibilidade_produtos_veiculos_variante_veiculo_id'), table_name='compatibilidade_produtos_veiculos')
    op.drop_index(op.f('ix_compatibilidade_produtos_veiculos_produto_id'), table_name='compatibilidade_produtos_veiculos')
    op.drop_table('compatibilidade_produtos_veiculos')
    op.drop_index(op.f('ix_variantes_veiculos_modelo_id'), table_name='variantes_veiculos')
    op.drop_table('variantes_veiculos')
    op.drop_index(op.f('ix_itens_pedido_produto_id'), table_name='itens_pedido')
    op.drop_index(op.f('ix_itens_pedido_pedido_id'), table_name='itens_pedido')
    op.drop_table('itens_pedido')
    op.drop_index(op.f('ix_itens_carrinho_produto_id'), table_name='itens_carrinho')
    op.drop_index(op.f('ix_itens_carrinho_carrinho_id'), table_name='itens_carrinho')
    op.drop_table('itens_carrinho')
    op.drop_index(op.f('ix_imagens_produtos_produto_id'), table_name='imagens_produtos')
    op.drop_table('imagens_produtos')
    op.drop_index(op.f('ix_eventos_usuario_id'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_sessao_id'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_nome_evento'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_index(op.f('ix_estoques_produto_id'), table_name='estoques')
    op.drop_table('estoques')
    op.drop_index(op.f('ix_especificacoes_produtos_produto_id'), table_name='especificacoes_produtos')
    op.drop_table('especificacoes_produtos')
    op.drop_index(op.f('ix_sessoes_usuario_id'), table_name='sessoes')
    op.drop_table('sessoes')
    op.drop_index(op.f('ix_produtos_slug'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_sku'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_marca_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_codigo_peca'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_categoria_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_ativo'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_pedidos_usuario_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_status'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_numero_pedido'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_modelos_veiculos_fabricante_id'), table_name='modelos_veiculos')
    op.drop_table('modelos_veiculos')
    op.drop_index(op.f('ix_enderecos_usuario_id'), table_name='enderecos')
    op.drop_table('enderecos')
    op.drop_index(op.f('ix_carrinhos_usuario_id'), table_name='carrinhos')
    op.drop_index(op.f('ix_carrinhos_sessao_id'), table_name='carrinhos')
    op.drop_table('carrinhos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_marcas_slug'), table_name='marcas')
    op.drop_table('marcas')
    op.drop_table('fabricantes_veiculos')
    op.drop_index(op.f('ix_categorias_slug'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_categoria_pai_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
